Result
amantulsyan35/know-your-anime pull request #4
Opened 2022-02-10 10:48 UTC by amantulsyan35

Result page for the final score

2022-02-21 16:51 UTC, parvez-rashid approved these changes
UI Review: Looks good, I feel there are too many borders for containers, it could've be a bit more subtle, just my perspective. The code looks great, well-structured and consistent. I do have a comment below, though not that important. Can be merged!

2022-02-21 16:51 UTC, parvez-rashid commented on Question/question.css
> +  display: flex;
You can use a utility class for setting `display: flex`. I can see you have used the property in many places, setting a utility class would be easier.

2022-02-21 16:53 UTC, yaswanthmyneni approved these changes
You can merge it after changes.

2022-02-21 16:53 UTC, yaswanthmyneni commented on Homepage/index.css
> +  border: 1px solid black;
changes: use css variables for colors

2022-02-21 16:53 UTC, yaswanthmyneni commented on Result/result.html
> +<!DOCTYPE html>
UI changes: the 1st question on the results page is showing two right options.
![Screenshot 2022-02-21 at 10 21 04 PM](https://user-images.githubusercontent.com/79623546/154997836-7caeda4e-de46-4369-97fb-93475e808692.png)

2022-02-21 22:27 UTC, pankaj-prog requested changes

2022-02-21 22:27 UTC, pankaj-prog commented on Homepage/index.css
> +  border: 1px solid rgb(0, 0, 0, 0.1);
use color variables

2022-02-21 22:27 UTC, pankaj-prog commented on Homepage/index.css
> +  box-shadow: 0 2px 2px 2px rgba(0, 0, 0, 0.1);
color variable here as well

2022-02-21 22:27 UTC, pankaj-prog commented on Homepage/index.html
> +      </div>
use semantic tags

2022-02-21 22:27 UTC, pankaj-prog commented on Homepage/index.css
> +  margin: 2rem 7rem 2rem 7rem;
you can use the shorthand property ( 2rem, 7rem )

2022-02-21 22:27 UTC, pankaj-prog commented on Homepage/index.html
> +    />
you can import multiple css in css and then import a single css in html document

2022-02-21 22:27 UTC, pankaj-prog commented on Result/result.html
> +            <p>Sakura</p>
use list for options

2022-02-21 22:28 UTC, manojsarna requested changes
overall its good!!

Do check the comments!!

2022-02-21 22:28 UTC, manojsarna commented on Homepage/index.css
> +  height: auto;
you can use short hand , for eg : margin 2rem 7rem;

2022-02-21 22:28 UTC, manojsarna commented on Homepage/index.css
> +  border: 1px solid black;
Use Color Variables to ease the process, you can change the values directly from the root , you dont have to change it manually!!

2022-02-21 22:28 UTC, manojsarna commented on Question/question.css
> +  height: auto;
check the margin values here also!!

2022-02-21 22:28 UTC, manojsarna commented on Question/question.css
> +  display: grid;
use color variables

2022-02-21 22:28 UTC, manojsarna commented on Question/question.css
> +  box-shadow: 0 2px 2px 2px rgba(0, 0, 0, 0.2);
check for color vars

2022-02-21 22:28 UTC, manojsarna commented on Result/result.css
> +  padding: 1rem;
check for margin

2022-02-21 22:28 UTC, manojsarna commented on Result/result.css
> +  padding: 1rem;
use color variables

2022-02-21 22:28 UTC, manojsarna commented on Result/result.css
> +  border: 1px solid rgb(0, 0, 0, 0.2);
check for  color variables

2022-02-21 22:28 UTC, manojsarna commented on Result/result.css
> +  padding: 1rem;
check for color variables

2022-02-21 22:28 UTC, manojsarna commented on Result/result.css
> +  border: 1px solid rgb(0, 0, 0, 0.2);
check here also

2022-02-22 05:15 UTC, eakansh125 approved these changes
Some minor changes can be done (not mandatory for now):
1. A utility class for flex can be defined
2. A margin can be provided between different results for a better UI

Rest looks good from my side!

2022-02-22 16:00 UTC, merged